<style>
h1, h1 *, 
h2, h2 *, 
h3, h3 *, 
h4, h4 *, 
h5, h5 *, 
h6, h6 * {
  font-family: "Times New Roman", Times, serif !important;
}
</style>

## **Optimising Marketing with Artificial Intelligence (OMAI)**

<style>
h1, h1 *, 
h2, h2 *, 
h3, h3 *, 
h4, h4 *, 
h5, h5 *, 
h6, h6 * {
  font-family: "Times New Roman", Times, serif !important;
}
</style>

### **Content-Based Recommendation System**

---

In [ ]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

pd.set_option('display.max_columns', None)

OMAI_mlrm_logregknn = pd.read_csv('OMAI - Results - MLRMs (LR & K-Nearest Neighbours) (Predictions).csv')
OMAI_mlrm_logregknn = OMAI_mlrm_logregknn.drop('Unnamed: 0', axis = 1)
OMAI_mlrm_logregknn.iloc[0:3]

In [ ]:
logreg_threshold = 0.55
OMAI_mlrm_logregknn['logreg_thresholds'] = np.where(OMAI_mlrm_logregknn['logreg_prob'].values >= logreg_threshold,
                                                  'Recommend', 'Not Recommend')
OMAI_mlrm_logregknn_reduced = (OMAI_mlrm_logregknn.loc[OMAI_mlrm_logregknn['logreg_thresholds'] == 'Recommend']
                             .sort_values(by = 'logreg_prob', ascending = False).copy())

In [ ]:
tfidf_rec = TfidfVectorizer(stop_words = 'english')
OMAI_mlrm_logregknn['description'] = OMAI_mlrm_logregknn['description'].fillna('')
tfidf_matrix_rec = tfidf_rec.fit_transform(OMAI_mlrm_logregknn['description'])
tfidf_matrix_rec.shape
tfidf_array_rec = tfidf_matrix_rec.toarray()
print(tfidf_array_rec)
cosine_similarity = linear_kernel(tfidf_matrix_rec, tfidf_matrix_rec)
cosine_similarity.shape
cosine_similarity[1]

In [ ]:
indices = pd.Series(OMAI_mlrm_logregknn.index, index = OMAI_mlrm_logregknn['title']).drop_duplicates()

def recommend_games(title, 
                    df_reduced = OMAI_mlrm_logregknn_reduced, 
                    cosine_similarity_matrix = cosine_similarity, 
                    top10recommendations = 10):
    
    idx = indices[title]  
    similarity_scores = list(enumerate(cosine_similarity_matrix[idx, :].ravel()))
    similarity_scores = sorted(similarity_scores, key = lambda x: x[1], reverse = True)
    similarity_scores = similarity_scores[1:]  
    position_to_score = dict(similarity_scores)

    positions = set(df_reduced.index)
    filtered_positions = [i for i, _ in similarity_scores if i in positions]

    return df_reduced.loc[filtered_positions, ['title', 'console', 'price', 'logreg_prob']] \
                     .assign(similarity_score = [position_to_score[i] for i in filtered_positions]) \
                     .head(top10recommendations)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[:,  
    ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[:,  
    ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = True).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['console'] == 'Xbox 360',
    ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['console'] == 'PlayStation 2',
    ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['console'] == 'PC & Mac',
    ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['console'] == 'Game Boy Advance',
    ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['console'] == 'GameCube',
    ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['price'] <= 20,
                                ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['price'] <= 20,
                                ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = True).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['price'] > 20,
                                ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[OMAI_mlrm_logregknn_reduced['price'] > 20,
                                ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = True).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[(OMAI_mlrm_logregknn_reduced['console'] == 'Xbox') &
                                (OMAI_mlrm_logregknn_reduced['price'] <= 20),
                                ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'logreg_prob', ascending = False).head(10)

In [ ]:
OMAI_mlrm_logregknn_reduced.loc[(OMAI_mlrm_logregknn_reduced['console'] == 'PlayStation 3') &
                                (OMAI_mlrm_logregknn_reduced['price'] > 20),
                                ['title', 'console', 'price', 'logreg_prob']].sort_values(by = 'price', ascending = False).head(10)

In [14]:
recommend_games("Super Mario 64 DS")

,title,console,price,logreg_prob,similarity_score
74,Mario Kart DS,Nintendo DS,29.54,0.993222,0.305531
195,New Super Mario Bros,Nintendo DS,32.00,0.990830,0.247860
526,Mario Hoops 3 On 3,Nintendo DS,41.74,0.826510,0.235033
885,Super Mario Advance,Game Boy Advance,79.99,0.981165,0.230824
406,Mario & Sonic at the Olympic Games,Nintendo Wii,49.38,0.933962,0.219314
1370,Mario & Luigi: Partners In Time,Nintendo DS,44.95,0.906187,0.209880
865,Diddy Kong Racing DS,Nintendo DS,33.99,0.743412,0.207725
290,Yoshi Touch and Go,Nintendo DS,46.49,0.870128,0.202615
699,Tetris DS,Nintendo DS,51.94,0.883008,0.198984
1258,Nanostray,Nintendo DS,17.95,0.668352,0.191583

In [34]:
recommendationexample1 = recommend_games("Super Mario 64 DS", top10recommendations = 50)

recommendationexample1_top10 = (recommendationexample1.query("console == 'Nintendo DS' and 5 <= price <= 30")
                                .head(10).reset_index(drop = True))

recommendationexample1_top10

,title,console,price,logreg_prob,similarity_score
0,Mario Kart DS,Nintendo DS,29.54,0.993222,0.305531
1,Nanostray,Nintendo DS,17.95,0.668352,0.191583
2,Touchmaster,Nintendo DS,13.00,0.963341,0.187996
3,Meteos,Nintendo DS,23.60,0.764378,0.141974
4,Castlevania Dawn of Sorrow,Nintendo DS,28.75,0.976882,0.134284
5,Clubhouse Games,Nintendo DS,18.20,0.945734,0.128579
6,Hotel Dusk: Room 215,Nintendo DS,29.68,0.804471,0.095276
7,My Word Coach,Nintendo DS,26.67,0.746903,0.083468
8,Brain Age: Train Your Brain in Minutes a Day!,Nintendo DS,13.99,0.574684,0.083325

In [16]:
recommend_games("Rollercoaster Tycoon 3")

,title,console,price,logreg_prob,similarity_score
1386,Rollercoaster Tycoon 3: Gold Compilation Pack,PC & Mac,19.61,0.574287,0.653565
1093,RollerCoaster Tycoon Gold Edition: RollerCoast...,PC & Mac,23.95,0.655515,0.394297
186,Roller Coaster Tycoon Expansion Pack: Loopy La...,PC & Mac,9.95,0.791723,0.379137
626,Rollercoaster Tycoon 3: Soaked! Expansion,PC & Mac,13.99,0.578184,0.375407
5,Roller Coaster Tycoon Expansion Pack: Corkscre...,PC & Mac,6.95,0.850402,0.361904
128,Sim Theme Park,PC & Mac,32.99,0.599915,0.342785
1021,Universal Studios Theme Park,GameCube,50.97,0.863265,0.331816
758,Thrillville,PlayStation 2,7.00,0.630988,0.330405
389,RollerCoaster Tycoon 2,PC & Mac,17.89,0.683484,0.327580
538,Rollercoaster Tycoon 3 Platinum,PC & Mac,16.53,0.866825,0.297860

In [35]:
recommendationexample2 = recommend_games("Rollercoaster Tycoon 3", top10recommendations = 50)

recommendationexample2_top10 = (recommendationexample2.query("console == 'PC & Mac' and 5 <= price <= 30")
                                .head(10).reset_index(drop = True))

recommendationexample2_top10

,title,console,price,logreg_prob,similarity_score
0,Rollercoaster Tycoon 3: Gold Compilation Pack,PC & Mac,19.61,0.574287,0.653565
1,RollerCoaster Tycoon Gold Edition: RollerCoast...,PC & Mac,23.95,0.655515,0.394297
2,Roller Coaster Tycoon Expansion Pack: Loopy La...,PC & Mac,9.95,0.791723,0.379137
3,Rollercoaster Tycoon 3: Soaked! Expansion,PC & Mac,13.99,0.578184,0.375407
4,Roller Coaster Tycoon Expansion Pack: Corkscre...,PC & Mac,6.95,0.850402,0.361904
5,RollerCoaster Tycoon 2,PC & Mac,17.89,0.683484,0.327580
6,Rollercoaster Tycoon 3 Platinum,PC & Mac,16.53,0.866825,0.297860
7,Roller Coaster Tycoon,PC & Mac,8.95,0.957648,0.206965
8,Zoo Tycoon Expansion Pack: Marine Mania,PC & Mac,24.69,0.736087,0.153136
9,Zoo Tycoon Complete Collection,PC & Mac,13.50,0.913308,0.124411

In [10]:
recommend_games("Battlefield: Vietnam")

,title,console,price,logreg_prob,similarity_score
508,Battlefield 2 The Complete Collection DVD,PC & Mac,5.99,0.655806,0.210539
819,Battlefield 2 Modern Combat,Xbox 360,22.94,0.834916,0.202940
896,Battlefield 1942: Deluxe Edition,PC & Mac,32.36,0.892963,0.195767
1087,Shell Shock: Nam '67,PlayStation 2,33.97,0.741913,0.194120
46,Joint Operations: Typhoon Rising,PC & Mac,11.10,0.616009,0.187984
223,Wings Over Vietnam,PC & Mac,14.92,0.656907,0.182239
79,Battlefield: 1942,PC & Mac,9.99,0.649052,0.148217
902,Operation Flashpoint: Cold War Crisis,PC & Mac,3.99,0.734391,0.126014
681,Vietcong,PC & Mac,17.89,0.707727,0.123816
153,Call of Duty: Game of the Year Edition,PC & Mac,11.99,0.847208,0.116852

In [36]:
recommendationexample3 = recommend_games("Battlefield: Vietnam", top10recommendations = 50)

recommendationexample3_top10 = (recommendationexample3.query("console == 'Xbox 360' and 5 <= price <= 30")
                                .head(10).reset_index(drop = True))

recommendationexample3_top10

,title,console,price,logreg_prob,similarity_score
0,Battlefield 2 Modern Combat,Xbox 360,22.94,0.834916,0.202940
1,Call of Duty 4: Modern Warfare,Xbox 360,29.98,0.975201,0.108401
2,Call of Duty 3,Xbox 360,24.54,0.823142,0.089667

In [17]:
recommend_games("Grand Theft Auto 3")

,title,console,price,logreg_prob,similarity_score
1,GREATEST HITS:Grand Theft Auto III,PlayStation 2,7.98,0.910993,0.525864
1245,Grand Theft Auto Vice City Stories,PlayStation Portable,14.55,0.952412,0.234040
740,Grand Theft Auto Liberty City Stories,PlayStation Portable,14.20,0.887262,0.220628
28,True Crime Streets of LA,PlayStation 2,22.98,0.661429,0.193973
1301,Grand Theft Auto: The Trilogy (Grand Theft Aut...,PlayStation 2,21.50,0.820799,0.187680
196,Grand Theft Auto IV,Xbox 360,16.99,0.887214,0.185222
377,Grand Theft Auto IV,PlayStation 3,16.72,0.893371,0.185222
69,Grand Theft Auto Vice City,PlayStation 2,8.98,0.876127,0.181681
246,Crazy Taxi,Sega Dreamcast,29.36,0.867359,0.154954
433,Grand Theft Auto: Vice City,PC & Mac,10.88,0.763248,0.141229

In [38]:
recommendationexample4 = recommend_games("Grand Theft Auto 3", top10recommendations = 50)

recommendationexample4_top10 = (recommendationexample4.query("console == 'PlayStation 2' and 5 <= price <= 30")
                                .head(10).reset_index(drop = True))

recommendationexample4_top10

,title,console,price,logreg_prob,similarity_score
0,GREATEST HITS:Grand Theft Auto III,PlayStation 2,7.98,0.910993,0.525864
1,True Crime Streets of LA,PlayStation 2,22.98,0.661429,0.193973
2,Grand Theft Auto: The Trilogy (Grand Theft Aut...,PlayStation 2,21.50,0.820799,0.187680
3,Grand Theft Auto Vice City,PlayStation 2,8.98,0.876127,0.181681
4,The Getaway,PlayStation 2,14.97,0.561097,0.109644
5,Grand Theft Auto San Andreas Greatest Hits,PlayStation 2,16.30,0.808775,0.105934
6,Gran Turismo 4,PlayStation 2,12.68,0.873506,0.101549
7,Godfather,PlayStation 2,19.98,0.715322,0.079953
8,Chaos Legion,PlayStation 2,29.98,0.600909,0.079683
9,Need for Speed Hot Pursuit 2,PlayStation 2,29.95,0.946183,0.078885

In [39]:
recommend_games("Virtua Tennis 3")

,title,console,price,logreg_prob,similarity_score
1330,Virtua Tennis,Sega Dreamcast,19.98,0.680517,0.485578
1393,Blazing Angels 2: Secret Missions of WWII,PlayStation 3,17.49,0.823615,0.252728
39,Mario Power Tennis,GameCube,58.49,0.926555,0.222006
415,Table Tennis,Xbox 360,8.99,0.820792,0.167205
917,Virtua Fighter 5,PlayStation 3,15.90,0.696892,0.160936
439,Ninja Gaiden Sigma,PlayStation 3,19.86,0.787016,0.143919
412,Top Spin,Xbox,9.97,0.841907,0.123123
1208,Lair,PlayStation 3,10.96,0.602722,0.087116
584,The Elder Scrolls IV: Oblivion,PlayStation 3,14.29,0.928442,0.083733
601,Killzone 2,PlayStation 3,18.67,0.841600,0.073967